/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as ClassicRouteImport } from './routes/classic'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorialModeRouteImport } from './routes/tutorial.$mode'
import { Route as PlayDropdokuRouteImport } from './routes/play.dropdoku'
import { Route as PlayClassicRouteImport } from './routes/play.classic'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicRoute = ClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialModeRoute = TutorialModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => TutorialRoute,
} as any)
const PlayDropdokuRoute = PlayDropdokuRouteImport.update({
  id: '/play/dropdoku',
  path: '/play/dropdoku',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayClassicRoute = PlayClassicRouteImport.update({
  id: '/play/classic',
  path: '/play/classic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/classic': typeof ClassicRoute
  '/daily': typeof DailyRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/personal': typeof PersonalRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tutorial': typeof TutorialRouteWithChildren
  '/play/classic': typeof PlayClassicRoute
  '/play/dropdoku': typeof PlayDropdokuRoute
  '/tutorial/$mode': typeof TutorialModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/classic': typeof ClassicRoute
  '/daily': typeof DailyRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/personal': typeof PersonalRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tutorial': typeof TutorialRouteWithChildren
  '/play/classic': typeof PlayClassicRoute
  '/play/dropdoku': typeof PlayDropdokuRoute
  '/tutorial/$mode': typeof TutorialModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/classic': typeof ClassicRoute
  '/daily': typeof DailyRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/personal': typeof PersonalRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tutorial': typeof TutorialRouteWithChildren
  '/play/classic': typeof PlayClassicRoute
  '/play/dropdoku': typeof PlayDropdokuRoute
  '/tutorial/$mode': typeof TutorialModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/battle'
    | '/classic'
    | '/daily'
    | '/explore'
    | '/leaderboard'
    | '/personal'
    | '/settings'
    | '/shop'
    | '/tutorial'
    | '/play/classic'
    | '/play/dropdoku'
    | '/tutorial/$mode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/battle'
    | '/classic'
    | '/daily'
    | '/explore'
    | '/leaderboard'
    | '/personal'
    | '/settings'
    | '/shop'
    | '/tutorial'
    | '/play/classic'
    | '/play/dropdoku'
    | '/tutorial/$mode'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/battle'
    | '/classic'
    | '/daily'
    | '/explore'
    | '/leaderboard'
    | '/personal'
    | '/settings'
    | '/shop'
    | '/tutorial'
    | '/play/classic'
    | '/play/dropdoku'
    | '/tutorial/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BattleRoute: typeof BattleRoute
  ClassicRoute: typeof ClassicRoute
  DailyRoute: typeof DailyRoute
  ExploreRoute: typeof ExploreRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PersonalRoute: typeof PersonalRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  TutorialRoute: typeof TutorialRouteWithChildren
  PlayClassicRoute: typeof PlayClassicRoute
  PlayDropdokuRoute: typeof PlayDropdokuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic': {
      id: '/classic'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial/$mode': {
      id: '/tutorial/$mode'
      path: '/$mode'
      fullPath: '/tutorial/$mode'
      preLoaderRoute: typeof TutorialModeRouteImport
      parentRoute: typeof TutorialRoute
    }
    '/play/dropdoku': {
      id: '/play/dropdoku'
      path: '/play/dropdoku'
      fullPath: '/play/dropdoku'
      preLoaderRoute: typeof PlayDropdokuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/classic': {
      id: '/play/classic'
      path: '/play/classic'
      fullPath: '/play/classic'
      preLoaderRoute: typeof PlayClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TutorialRouteChildren {
  TutorialModeRoute: typeof TutorialModeRoute
}

const TutorialRouteChildren: TutorialRouteChildren = {
  TutorialModeRoute: TutorialModeRoute,
}

const TutorialRouteWithChildren = TutorialRoute._addFileChildren(
  TutorialRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BattleRoute: BattleRoute,
  ClassicRoute: ClassicRoute,
  DailyRoute: DailyRoute,
  ExploreRoute: ExploreRoute,
  LeaderboardRoute: LeaderboardRoute,
  PersonalRoute: PersonalRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  TutorialRoute: TutorialRouteWithChildren,
  PlayClassicRoute: PlayClassicRoute,
  PlayDropdokuRoute: PlayDropdokuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
